# Install dependencies only when needed
FROM node:alpine AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile


# Rebuild the source code only when needed
FROM node:alpine AS builder
WORKDIR /app
COPY . .
COPY --from=deps /app/node_modules ./node_modules
ARG NODE_ENV=devolpement
RUN echo ${NODE_ENV}
RUN NODE_ENV=${NODE_ENV} yarn build

# Production image, copy all the files and run next
FROM node:alpine AS runner
WORKDIR /app
RUN addgroup -g 1001 -S nodejs
RUN adduser -S nextjs -u 1001

# You only need to copy next.config.js if you are NOT using the default configuration
COPY --from=builder /app/next.config.js ./next.config.js
COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/src ./src
COPY --from=builder /app/styles ./styles
COPY --from=builder /app/next-env.d.ts ./next-env.d.ts

USER nextjs
ARG PORT=3000
EXPOSE ${PORT}
# Expose (for some reason, Azure Spring Apps requires port 1025)
# EXPOSE 1025

# Parameterize env variables
ENV VIRTUAL_CUSTOMERS_URL=http://localhost:8091
ENV ORDERS_URL=http://localhost:8082
ENV ACCOUNTING_URL=http://localhost:8087
ENV OPENAI_URL=http://127.0.0.1:8000

# Start next
CMD ["yarn", "start"]
