apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: miyagi
  labels:
    name: frontend
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 3000
  selector:
    app: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: miyagi
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: "ghcr.io/azure-samples/miyagi/frontend-service:latest"
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "0.5"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
          readinessProbe:
            httpGet:
              path: /probes/ready
              port: 3000
            timeoutSeconds: 30
            successThreshold: 1
            failureThreshold: 12
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /probes/healthz
              port: 3000
            failureThreshold: 6
            periodSeconds: 10