version: '3.8'

services:
    memory-service:
        build: .
        ports:
            - "8080:8080"
        volumes:
            - .:/usr/src/app
    qdrant:
        image: qdrant/qdrant:latest
        ports:
            - "6333:6333"
