FROM openjdk:17-jdk-alpine
# Secure way to run the container as non-root user
RUN apk add dumb-init
RUN mkdir /app
RUN addgroup --system miyagiuser && adduser -S -s /bin/false -G miyagiuser miyagiuser
COPY target/*.jar /app/app.jar
WORKDIR /app
RUN chown -R miyagiuser:miyagiuser /app
USER miyagiuser
ARG PORT=8702
EXPOSE ${PORT}
CMD "dumb-init" "java" "-jar" "app.jar"