apiVersion: apps/v1
kind: Deployment
metadata:
  name: miyagi-recommendation
  labels:
    app: miyagi-recommendation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: miyagi-recommendation
  template:
    metadata:
      labels:
        app: miyagi-recommendation
    spec:
      containers:
      - name: miyagi-recommendation
        image: zmiyagi1acr1tqgrlvhlvdnde.azurecr.io/miyagi-recommendation:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080