name: Automate K8s Infra Provisioning

on:
  push:
    branches:
      - rk/infra-automation
    paths:
      - 'infrastructure/kubernetes'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Ingress-Nginx Controller
      shell: bash
      env:
        repo_name: ingress-nginx
        deployment_name: ingress-nginx
        chart_name: ingress-nginx
        namespace: ingress-nginx
        repo_url: https://kubernetes.github.io/ingress-nginx
        version: 4.6.1
      run: | 
        helm repo add $repo_name $repo_url
        helm repo update
        helm upgrade \
          $deployment_name \
          $repo_name/$chart_name \
          --namespace $namespace \
          --generate-namespace \
          --version $version
    
    - name: Install External DNS Provider
      shell: bash
      env:
        repo_name: bitnami
        deployment_name: external-dns
        chart_name: external-dns
        namespace: external-dns
        repo_url: https://charts.bitnami.com/bitnami
        version: 0.13.5
      run: |
        helm repo add bitnami $repo_url
        helm repo update
        helm upgrade \
          $deployment_name \
          $repo_name/$chart_name \
          --namespace $namespace \
          --generate-namespace \
          --version $version

    - name: Install Cert-Manager
      shell: bash
      env:
        repo_name: jetstack
        repo_url: https://charts.jetstack.io
        chart_name: cert-manager
        namespace: cert-manager
        version: 1.12.1
      run: |
        helm repo add $repo_name $repo_url
        helm repo update
        helm install \
          $deployment_name \
          $repo_name/$chart_name \
          --namespace $namespace \
          --generate-namespace \
          --version $version \ 
          --set installCRDs=true
