name: User Service Build and Push to GHCR

on:
  push:
    branches:
      - main
    paths:
      - 'services/user-service/java/**'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  REPOSITORY: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.main.outputs.version }}
      created: ${{ steps.main.outputs.created }}
      project: ${{ steps.main.outputs.project }}
      image: ${{ steps.main.outputs.image }}
      repository: ${{ steps.main.outputs.repository }}  
    steps:
    - name: Checkout code
      uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0
    - name: Set short_sha
      id: vars
      run: echo "short_sha=$(git rev-parse --short HEAD)" >> ${GITHUB_ENV}
    - name: Login to GHCR
      uses: docker/login-action@dd4fa0671be5250ee6f50aedf4cb05514abda2c7 # v1.14.1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: downcase env.REPOSITORY
      run: |
        echo "REPOSITORY=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
    - name: Setup Java
      uses: actions/setup-java@e9fbacdec3bb3b6036605a3e6f7995d66773a8c6 # v3.14.2
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'
    - name: Set up Maven
      uses: stCarolas/setup-maven@07fbbe97d97ef44336b7382563d66743297e442f # v4.5
      with:
        maven-version: 3.8.2
    - name: Build with Maven
      run: mvn -B package --file ./services/user-service/java/pom.xml -DskipTests
    - name: Build and push Docker image
      uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a # v2.10.0
      with:
        context: services/user-service/java
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.REPOSITORY }}/user-service:${{ env.short_sha }}
